name: scheiber
slug: scheiber
version: "2.0.6"
description: >
  Interface to scheiber

arch:
  - amd64
  - armv7
  - aarch64

startup: services
init: false
host_network: true

privileged:
  - NET_ADMIN
  - SYS_RAWIO

map:
  - type: homeassistant_config
    read_only: False
    path: /custom/config/path

options:
  can_interface: can1
  mqtt_host: localhost
  mqtt_port: 1883
  mqtt_user: mqtt_user
  mqtt_password: mqtt
  mqtt_topic_prefix: homeassistant
  log_level: info
  data_dir: /data

schema:
  can_interface: str
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mqtt_topic_prefix: str
  log_level: list(info|debug|warning|error)
  data_dir: str?
